version = '0.1.0'

[[files."CHANGELOG.rst"]]
search = """
`Unreleased`_
*************
"""
replace = """
`Unreleased`_
*************

{{new_version}} - {{utcnow | strftime('%Y-%m-%d')}}
******************
"""

[[files."CHANGELOG.rst"]]
search = """
.. _`Unreleased`: https://github.com/luismayta/slide-git4devs/compare/{{old_version}}...HEAD
"""
replace = """
.. _`Unreleased`: https://github.com/luismayta/slide-git4devs/compare/{{new_version}}...HEAD
.. _{{new_version}}: https://github.com/luismayta/slide-git4devs/compare/{{old_version}}...{{new_version}}
"""
