-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: c8a1c91c762b8e24fdc5a33455ec10662f523328
    hooks:
    -   id: detect-private-key
        files: ^(?!\.?git-crypt)
    -   id: check-merge-conflict
    -   id: trailing-whitespace
        files: ^tf|-|\.(py|tfvars|tf|tfenv|env|yml|yaml|pem|key|mock)$
    -   id: end-of-file-fixer
        files: ^tf|-|\.(py|tfvars|tf|tfenv|env|yml|yaml|pem|key|mock)$
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: check-ast
    -   id: debug-statements
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E501
    -   id: double-quote-string-fixer
    -   id: check-docstring-first
    -   id: pretty-format-json
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: name-tests-test
-   repo: git://github.com/pre-commit/mirrors-scss-lint
    sha: v0.50.2
    hooks:
    -   id: scss-lint
        files: \.(scss)$
-   repo: git@github.com:pre-commit/pre-commit
    sha: bbf1f62ed686a3e321280703a227fbd957e76151
    hooks:
    -   id: validate_config
    -   id: validate_manifest
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: 1.0.4
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
