language: python

os:
  - osx
  - linux

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

sudo: true

before_install:
  - if [[ "$(uname -s)" == 'Linux' ]]; then
      travis_retry sudo apt-get update -qq;
      sudo apt-get install python-pip -y;
    fi
  - if [[ "$(uname -s)" == 'Darwin' ]]; then
      travis_retry brew update;
      brew install pip;
    fi

install:
  make install env=test

script:
  make lint
  make test

notifications:
  email: false

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
